### ISSUE TITLE
SCSS va changer vos vies.

### ISSUE THREAD

**Issue by tarocafe** [OpenO1/frameworks#1]
Pas vraiment une Issue, mais un stylesheet en CSS devient généralement le bordel après un certain temps.
En gros SCSS et ses fonctionnalités permet en quelque sorte de régler ce problème.

https://sass-lang.com/guide

ctou, je pense que le guide explique assez bien comment ça fonctionne

**Comment by tarocafe** [comment]
d'ailleurs, https://www.reddit.com/r/web_design/comments/shfzk3/website_fined_by_german_court_for_leaking/

**Comment by tarocafe** [comment]
Avec SCSS, ceci:
```CSS
body {
    /*background-color: #14141a;*/
}

body::-webkit-scrollbar
{
    width: 0.45rem;
}
body::-webkit-scrollbar-track
{
    background: #121217;
}
body::-webkit-scrollbar-thumb
{
    background: #22222d;
}
```
... peut devenir cela:
```SCSS
body {
    /*background-color: #14141a;*/
    
    &::-webkit-scrollbar
    {
        width: 0.45rem;
    }
    &::-webkit-scrollbar-track
    {
        background: #121217;
    }
    &::-webkit-scrollbar-thumb
    {
        background: #22222d;
    }
}
```
Ce qui rend le code plus agréable à lire

Après j'avoue c'est pas très impressionnant avec cet example mais voilà ,-,
